/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiSource } from './apiSource';


export interface ApiCustomURL { 
    source?: ApiSource;
    url?: string;
}
export namespace ApiCustomURL {
}


