/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ArchiverImageStatus = {
    ImageStatusSuccess: 'success',
    ImageStatusFailed: 'failed'
} as const;
export type ArchiverImageStatus = typeof ArchiverImageStatus[keyof typeof ArchiverImageStatus];

