/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ArchiverChapterStatus = {
    ChapterStatusSuccess: 'success',
    ChapterStatusIncomplete: 'incomplete',
    ChapterStatusFailed: 'failed'
} as const;
export type ArchiverChapterStatus = typeof ArchiverChapterStatus[keyof typeof ArchiverChapterStatus];

