/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArchiverImageStatus } from './archiverImageStatus';


export interface ArchiverImageReport { 
    page?: number;
    /**
     * non-empty only on failure
     */
    reason?: string;
    status?: ArchiverImageStatus;
    url?: string;
}
export namespace ArchiverImageReport {
}


