/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiSource } from './apiSource';


export interface HandlersDownloadRequest { 
    /**
     * ChapterIDs is the list of chapter IDs to download. Must contain at least one entry.
     */
    chapter_ids?: Array<string>;
    /**
     * Slug is the source-specific toon slug.
     */
    slug?: string;
    /**
     * Source is the API client to use (e.g. \"asura\", \"nato\").
     */
    source?: ApiSource;
    /**
     * URL is an optional custom base URL to try before the client\'s configured URLs.
     */
    url?: string;
}
export namespace HandlersDownloadRequest {
}


