/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HandlersDownloadResponse { 
    /**
     * RuntimeID is the WebSocket runtime ID the caller should connect to in order to receive live progress packets.
     */
    runtime_id?: string;
}

