/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiSource } from './apiSource';


export interface HandlersSearchRequest { 
    /**
     * Input is the search query string.
     */
    input?: string;
    /**
     * Sources is the list of API clients to query. Valid values: \"asura\". Must contain at least one entry.
     */
    sources?: Array<ApiSource>;
}

