/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiSource } from './apiSource';
import { ApiCustomURL } from './apiCustomURL';


export interface HandlersSearchRequest { 
    /**
     * CustomURLs allows the caller to provide one extra base URL per source. Each entry is tried before the client\'s own configured URLs. At most one entry per source is accepted.
     */
    custom_urls?: Array<ApiCustomURL>;
    /**
     * Input is the search query string.
     */
    input?: string;
    /**
     * Sources is the list of API clients to query. Valid values: \"asura\", \"nato\". Must contain at least one entry.
     */
    sources?: Array<ApiSource>;
}

