/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiSource } from './apiSource';


export interface HandlersFetchRequest { 
    /**
     * Slug is the source-specific toon slug (e.g. \"0a59965f-some-toon-slug\").
     */
    slug?: string;
    /**
     * Source is the API client to use (e.g. \"asura\").
     */
    source?: ApiSource;
}
export namespace HandlersFetchRequest {
}


