/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToonruntimePacketType } from './toonruntimePacketType';


export interface ToonruntimePacketCompleted { 
    /**
     * URL to GET the assembled archive file
     */
    archive_url?: string;
    hash?: string;
    /**
     * Total chapters that were downloaded
     */
    total?: number;
    type?: ToonruntimePacketType;
}
export namespace ToonruntimePacketCompleted {
}


