/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArchiverChapterStatus } from './archiverChapterStatus';
import { ArchiverImageReport } from './archiverImageReport';
import { ToonruntimePacketType } from './toonruntimePacketType';


export interface ToonruntimePacketChapterReport { 
    /**
     * display name, e.g. \"Chapter 001\"
     */
    chapter?: string;
    chapter_id?: string;
    hash?: string;
    /**
     * omitted on full success
     */
    images?: Array<ArchiverImageReport>;
    /**
     * non-empty on failed/incomplete
     */
    reason?: string;
    status?: ArchiverChapterStatus;
    type?: ToonruntimePacketType;
}
export namespace ToonruntimePacketChapterReport {
}


