/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ToonSearchResult { 
    cover_url?: string;
    /**
     * ID is the source-specific identifier (opaque to the caller).
     */
    id?: string;
    /**
     * Source is the name of the API client that produced this result.
     */
    source?: string;
    source_url?: string;
    title?: string;
}

