/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ToonSource = {
    SourceAsura: 'asura',
    Asura2: 'asura'
} as const;
export type ToonSource = typeof ToonSource[keyof typeof ToonSource];

