/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToonruntimePacketType } from './toonruntimePacketType';


export interface ToonruntimePacketZipping { 
    /**
     * Total number of chapters being zipped
     */
    chapters?: number;
    /**
     * Archive format: \"pdf\", \"cbz\", or \"images\"
     */
    format?: string;
    hash?: string;
    type?: ToonruntimePacketType;
}
export namespace ToonruntimePacketZipping {
}


