/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ToonFetchErrorStep = {
    FetchErrorSearch: 1,
    FetchErrorFetch: 2,
    FetchErrorDownload: 3,
    FetchErrorArchive: 4,
    FetchErrorUnknown: 5
} as const;
export type ToonFetchErrorStep = typeof ToonFetchErrorStep[keyof typeof ToonFetchErrorStep];

