/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ToonStatus = {
    StatusUnknown: 'unknown',
    StatusOngoing: 'ongoing',
    StatusCompleted: 'completed',
    StatusHiatus: 'hiatus',
    StatusDropped: 'dropped',
    StatusSeasonEnd: 'season_end'
} as const;
export type ToonStatus = typeof ToonStatus[keyof typeof ToonStatus];

