/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToonChapter } from './toonChapter';


export interface ToonToon { 
    author?: string;
    /**
     * Chapters is populated only when fetching full toon details.
     */
    chapters?: Array<ToonChapter>;
    cover_url?: string;
    description?: string;
    /**
     * ID is the source-specific identifier.
     */
    id?: string;
    source?: string;
    source_url?: string;
    title?: string;
}

