/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToonStatus } from './toonStatus';
import { ToonSource } from './toonSource';


export interface ToonSearchResult { 
    cover_url?: string;
    /**
     * ID is the source-specific identifier (opaque to the caller).
     */
    id?: string;
    /**
     * LastChapter is the latest chapter number available, 0 if unknown.
     */
    last_chapter?: number;
    /**
     * Rating is the community rating (e.g. 9.3), 0 if unknown.
     */
    rating?: number;
    /**
     * Source is the API client that produced this result.
     */
    source?: ToonSource;
    source_url?: string;
    /**
     * Status is the publication status of the toon.
     */
    status?: ToonStatus;
    title?: string;
}
export namespace ToonSearchResult {
}


