/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToonruntimePacketType } from './toonruntimePacketType';


export interface ToonruntimePacketProgress { 
    /**
     * Items completed so far in this phase
     */
    done?: number;
    hash?: string;
    /**
     * Populated only during the chapters phase
     */
    items?: Array<object>;
    /**
     * \"chapters\" or \"images\"
     */
    phase?: string;
    /**
     * Total items in this phase
     */
    total?: number;
    type?: ToonruntimePacketType;
}
export namespace ToonruntimePacketProgress {
}


