/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToonPage } from './toonPage';


export interface ToonChapter { 
    date?: string;
    /**
     * ID is the source-specific identifier.
     */
    id?: string;
    /**
     * float to support \"12.5\" style chapters
     */
    number?: number;
    /**
     * Pages is populated only when downloading a chapter\'s images.
     */
    pages?: Array<ToonPage>;
    title?: string;
    url?: string;
}

