/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ToonruntimePacketType = {
    PacketTypeInit: 'init',
    PacketTypeFatal: 'fatal',
    PacketTypeProgress: 'progress',
    PacketTypeCompleted: 'completed'
} as const;
export type ToonruntimePacketType = typeof ToonruntimePacketType[keyof typeof ToonruntimePacketType];

