/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToonruntimePacketType } from './toonruntimePacketType';


export interface ToonruntimePacket { 
    hash?: string;
    type?: ToonruntimePacketType;
}
export namespace ToonruntimePacket {
}


