/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToonruntimePacketType } from './toonruntimePacketType';
import { ToonFetchErrorStep } from './toonFetchErrorStep';


export interface ToonruntimePacketFatal { 
    hash?: string;
    message?: string;
    step?: ToonFetchErrorStep;
    type?: ToonruntimePacketType;
}
export namespace ToonruntimePacketFatal {
}


