/**
 * Offtoon API
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToonruntimePacket } from './toonruntimePacket';
import { ToonruntimePacketCompleted } from './toonruntimePacketCompleted';
import { ToonruntimePacketProgress } from './toonruntimePacketProgress';
import { ToonruntimePacketInit } from './toonruntimePacketInit';
import { ToonruntimePacketFatal } from './toonruntimePacketFatal';


export interface ToonruntimePacketSpec { 
    packet?: ToonruntimePacket;
    packetCompleted?: ToonruntimePacketCompleted;
    packetFatal?: ToonruntimePacketFatal;
    packetInit?: ToonruntimePacketInit;
    packetProgress?: ToonruntimePacketProgress;
}

